apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: haystack-rag
    component: backend
  name: backend-files
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: haystack-rag
    component: backend
  name: backend-pipelines
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
