FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/common/ /app/common/
COPY src/query/ /app/query/

EXPOSE 8002

CMD ["uvicorn", "query.main:app", "--host", "0.0.0.0", "--port", "8002"]
