# Pre-existing secret with opensearch password (OPENSEARCH_PASSWORD)
secretName: opensearch-password

opensearch:
  # Enable the bundled opensearch. Default is to manage opensearch externally
  enable: false

persistence:
  enabled: false
